import Head from 'next/head'

export default function Confirmed() {

  return (
    <div>
      <Head>
        <title>Confirmed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      Confirmed
    </div>
  )
}
